Document: snapd-xdg-open
Title: Debian snapd-xdg-open Manual
Author: <insert document author here>
Abstract: This manual describes what snapd-xdg-open is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snapd-xdg-open/snapd-xdg-open.sgml.gz

Format: postscript
Files: /usr/share/doc/snapd-xdg-open/snapd-xdg-open.ps.gz

Format: text
Files: /usr/share/doc/snapd-xdg-open/snapd-xdg-open.text.gz

Format: HTML
Index: /usr/share/doc/snapd-xdg-open/html/index.html
Files: /usr/share/doc/snapd-xdg-open/html/*.html
